# Generated by Django 3.0 on 2020-05-28 22:25

from django.db import migrations, models
import django.db.models.deletion
import main.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_merge_20200526_2318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalfile',
            options={'verbose_name': 'Дотатковий матеріал', 'verbose_name_plural': 'Додаткові матеріали'},
        ),
        migrations.AlterModelOptions(
            name='additionalimage',
            options={'verbose_name': 'Додаткове зображення', 'verbose_name_plural': 'Додаткові зображення'},
        ),
        migrations.AlterModelOptions(
            name='additionalschedule',
            options={'verbose_name': 'Продовження розкладу', 'verbose_name_plural': 'Продовження розклду'},
        ),
        migrations.AlterModelOptions(
            name='advuser',
            options={'ordering': ['last_name'], 'verbose_name': 'Студент', 'verbose_name_plural': 'Студенти'},
        ),
        migrations.AlterModelOptions(
            name='auditory',
            options={'ordering': ['auditory_number'], 'verbose_name': 'Аудиторія', 'verbose_name_plural': 'Аудиторії'},
        ),
        migrations.AlterModelOptions(
            name='bb',
            options={'ordering': ['-created_at'], 'verbose_name': 'Оголошення', 'verbose_name_plural': 'Оголошення'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Коментарій', 'verbose_name_plural': 'Коментарі'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Розклад', 'verbose_name_plural': 'Розклад'},
        ),
        migrations.AlterModelOptions(
            name='structure',
            options={'ordering': ['structure_name'], 'verbose_name': 'Учбовий корпус', 'verbose_name_plural': 'Учбові корпуса'},
        ),
        migrations.AlterModelOptions(
            name='subgroup',
            options={'ordering': ['super_group__order', 'super_group__name', 'order', 'name'], 'verbose_name': 'Група', 'verbose_name_plural': 'Групи'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name_of_subject'], 'verbose_name': 'Дисципліна', 'verbose_name_plural': 'Дисципліни'},
        ),
        migrations.AlterModelOptions(
            name='supergroup',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Форма навчання', 'verbose_name_plural': 'Форми навчання'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['last_name', 'first_name', 'middle_name'], 'verbose_name': 'Викладач', 'verbose_name_plural': 'Викладачі'},
        ),
        migrations.AlterField(
            model_name='additionalfile',
            name='file',
            field=models.FileField(upload_to=main.utilities.get_namestamp_path, verbose_name='Матеріал'),
        ),
        migrations.AlterField(
            model_name='additionalfile',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Subject', verbose_name='Дисципліна'),
        ),
        migrations.AlterField(
            model_name='additionalimage',
            name='bb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Bb', verbose_name='Оголошення'),
        ),
        migrations.AlterField(
            model_name='additionalimage',
            name='image',
            field=models.ImageField(upload_to=main.utilities.get_timestamp_path, verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='additionalschedule',
            name='auditory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.Auditory', verbose_name='Аудиторія'),
        ),
        migrations.AlterField(
            model_name='additionalschedule',
            name='day',
            field=models.CharField(choices=[('0', 'Понеділок'), ('1', 'Вівторок'), ('2', 'Середа'), ('3', 'Четвер'), ('4', "П'ятниця"), ('5', 'Субота')], max_length=1, null=True, verbose_name='День тижня'),
        ),
        migrations.AlterField(
            model_name='additionalschedule',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Schedule', verbose_name='Розклад'),
        ),
        migrations.AlterField(
            model_name='additionalschedule',
            name='start_time',
            field=models.CharField(choices=[('08:30:00', '08:30:00'), ('10:25:00', '10:25:00'), ('12:35:00', '12:35:00'), ('14:30:00', '14:30:00'), ('16:25:00', '16:25:00'), ('18:10:00', '18:10:00')], max_length=10, null=True, verbose_name='Початок заняття'),
        ),
        migrations.AlterField(
            model_name='additionalschedule',
            name='structure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.Structure', verbose_name='Учбовий корпус'),
        ),
        migrations.AlterField(
            model_name='additionalschedule',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.Subject', verbose_name='Дисципліна'),
        ),
        migrations.AlterField(
            model_name='additionalschedule',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Teacher', verbose_name='Викладач'),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.SubGroup', verbose_name='Група'),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='is_activated',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Пройшов активацію?'),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='is_teacher',
            field=models.BooleanField(default=False, verbose_name='Викладач'),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='send_messages',
            field=models.BooleanField(default=True, verbose_name='Слати оповещанія про нові коментарі?'),
        ),
        migrations.AlterField(
            model_name='auditory',
            name='auditory_number',
            field=models.CharField(max_length=5, verbose_name='Аудиторія'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Teacher', verbose_name='Автор оголошення'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='content',
            field=models.TextField(verbose_name='Інформація'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубліковано'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.SubGroup', verbose_name='Група'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='image',
            field=models.ImageField(blank=True, upload_to=main.utilities.get_timestamp_path, verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Виводити на головній сторінці?'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='bb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Bb', verbose_name='Оголошення'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='Зміст'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опублікован'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Виводити на головній сторінці?'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='group',
            name='super_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.SuperGroup', verbose_name='Форма навчання'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.SubGroup', verbose_name='Група'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='structure_name',
            field=models.CharField(max_length=15, verbose_name='Учбовий корпус'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name_of_subject',
            field=models.CharField(max_length=220, verbose_name='Назва дисципліни'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='degree',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ступінь'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='middle_name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='По батькові'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='position',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Посада'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='rank',
            field=models.CharField(blank=True, max_length=40, verbose_name='Звання'),
        ),
        migrations.AlterUniqueTogether(
            name='additionalschedule',
            unique_together={('structure', 'auditory', 'start_time', 'day')},
        ),
    ]
