# Generated by Django 3.0 on 2020-05-29 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20200529_0125'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='additionalschedule',
            unique_together={('schedule', 'structure', 'auditory', 'start_time', 'day')},
        ),
    ]
