# Generated by Django 3.0 on 2020-05-29 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_auto_20200529_2229'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='additionalschedule',
            unique_together={('subject_id', 'schedule_id', 'structure', 'auditory', 'start_time', 'day')},
        ),
    ]
