# Generated by Django 3.0 on 2020-05-29 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_auto_20200529_2236'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='additionalschedule',
            unique_together={('subject_id', 'structure', 'auditory', 'start_time', 'day')},
        ),
    ]
