# Generated by Django 3.0 on 2020-05-29 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_auto_20200529_2243'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='additionalschedule',
            unique_together={('schedule_id', 'structure', 'auditory', 'start_time', 'day')},
        ),
    ]
