# Generated by Django 3.0 on 2020-05-29 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_auto_20200529_2244'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='additionalschedule',
            unique_together={('schedule_id', 'subject', 'structure', 'auditory', 'start_time', 'day')},
        ),
    ]
