# Generated by Django 3.0 on 2020-05-30 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_auto_20200529_2249'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='additionalschedule',
            unique_together=set(),
        ),
    ]
