# Generated by Django 3.0 on 2020-05-30 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_auto_20200530_1100'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='additionalschedule',
            unique_together={('schedule_id', 'subject', 'structure', 'auditory', 'start_time', 'day')},
        ),
    ]
